=== kvranjith01/common-ansible/ansible/roles/nginx/files/xmlconfig/dynamicproperties.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.0.7 NT (http://www.xmlspy.com) by Ben Burdsall (Accenture) -->
<!ELEMENT ALL (GROUP*, PROPERTY*)>
<!ELEMENT GROUP (GROUP*, PROPERTY*)>
<!ELEMENT PROPERTY (#PCDATA)>
<!ATTLIST PROPERTY
	name CDATA #REQUIRED
	type (String | int | float | boolean) #REQUIRED
>
<!ATTLIST GROUP
	name CDATA #REQUIRED
>

=== kvranjith01/common-ansible/ansible/roles/jboss/files/xmlconfig/dynamicproperties.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ALL SYSTEM "dynamicproperties.dtd">
<ALL>
  <GROUP name="Component Factory">
    <!-- Common Properties used by most Components -->
    <GROUP name="Common">
      <PROPERTY name="saxparser" type="String">com.sun.xml.parser.ValidatingParser</PROPERTY>
      <PROPERTY name="domparserresolver" type="String">com.sun.xml.parser.Resolver</PROPERTY>
    </GROUP>
    <!--- end of Common Group -->
    <!-- Logger settings -->
    <GROUP name="Logger">
      <GROUP name="general">
        <PROPERTY name="cfloggerfile" type="String">/prod/applc/wls/sqdirect/sqdirect/dist/logs/logger/debug.log</PROPERTY>
        <PROPERTY name="cfeventfile" type="String">/prod/applc/wls/sqdirect/sqdirect/dist/logs/event/event.log</PROPERTY>
        <PROPERTY name="cfperformancelogfile" type="String">/prod/applc/wls/sqdirect/sqdirect/dist/logs/performance/performance.log</PROPERTY>
        <PROPERTY name="cfaccessperformancelogfile" type="String">/prod/applc/wls/sqdirect/sqdirect/dist/logs/accessperformance/accessperformance.log</PROPERTY>
        <PROPERTY name="cfloggerclass" type="String">com.singaporeair.cf.logger.FileLogger</PROPERTY>
    <PROPERTY name="cfsysadmindirectorypath" type="String">/prod/applc/wls/sqdirect/sqdirect/dist/logs/log/</PROPERTY>
    <PROPERTY name="cfloghome" type="String">/prod/applc/wls/sqdirect/sqdirect/dist/logs/log/</PROPERTY>
    <PROPERTY name="cfeventhome" type="String">/prod/applc/wls/sqdirect/sqdirect/dist/logs/event/</PROPERTY>
      </GROUP>
      <!-- Logging states for Logger starts -->
      <GROUP name="loggingstate">
        <PROPERTY name="cferrorstate" type="String">true</PROPERTY>
        <PROPERTY name="cfwarningstate" type="String">true</PROPERTY>
        <PROPERTY name="cfinfostate" type="String">false</PROPERTY>
        <PROPERTY name="cfeventstate" type="String">false</PROPERTY>
        <PROPERTY name="cfscreenstate" type="String">true</PROPERTY>
        <PROPERTY name="cfperformancelog" type="String">false</PROPERTY>
        <PROPERTY name="cfaccessperformancelog" type="String">false</PROPERTY>
      </GROUP>
      <!-- Logging states for Logger ends -->
    </GROUP>
    <!-- end of Logger settings -->
    <!-- scheduler componet defines the period for specific classes to be automatically called under the weblogic time API -->
    <GROUP name="Scheduler">
      <!-- The Dynamic properties should be reloaded once every minute -->
      <GROUP name="DynaProp">
        <PROPERTY name="class" type="String">com.singaporeair.cf.dynaprop.DynaProp</PROPERTY>
        <PROPERTY name="every" type="int">1</PROPERTY>
      </GROUP>


      <!-- Start Singleton, Configuration of this Should appear before other components which actually uses this-->
      <GROUP name="SingletonRegistry">
        <PROPERTY name="class" type="String">com.singaporeair.cf.singleton.SingletonRegistry</PROPERTY>
        <PROPERTY name="every" type="int">5</PROPERTY>
      </GROUP>
      <!-- end Singleton -->
        <!-- The Formvalidator should be reloaded once every 2 hours -->
        <GROUP name="FormValidator">
          <PROPERTY name="class" type="String">com.singaporeair.cf.formvalidator.FormSet</PROPERTY>
          <PROPERTY name="every" type="int">1</PROPERTY>
        </GROUP>
      <!-- The DataProvide should be reloaded once every 2 hours -->
      <GROUP name="DataProvider">
        <PROPERTY name="class" type="String">com.singaporeair.cf.dataprovider.QueryMapperScheduler</PROPERTY>
        <PROPERTY name="every" type="int">1</PROPERTY>
      </GROUP>
      <GROUP name="PreloadCache">
        <PROPERTY name="class" type="String">com.singaporeair.cf.dataprovider.PreloadCache</PROPERTY>
        <PROPERTY name="every" type="int">60</PROPERTY>
      </GROUP>
      <GROUP name="AccessLogger">
        <PROPERTY name="class" type="String">com.singaporeair.mysia.arch.sqaccess.AccessLogger</PROPERTY>
        <PROPERTY name="every" type="int">1</PROPERTY>
      </GROUP>
      <GROUP name="HostCheck">
        <PROPERTY name="class" type="String">com.singaporeair.mysia.arch.squtil.HostCheck</PROPERTY>
        <PROPERTY name="every" type="int">10000</PROPERTY>
      </GROUP>
      <GROUP name="ServerCheck">
        <PROPERTY name="class" type="String">com.singaporeair.mysia.arch.squtil.ServerCheck</PROPERTY>
        <PROPERTY name="every" type="int">10000</PROPERTY>
      </GROUP>
      
     <GROUP name="BookingStatusTracker">
        <!-- Sets the booking status tracker schedule -->
        <PROPERTY name="class" type="String">com.singaporeair.mysia.bookingstatustracker.BookingStatusTrackerScheduler</PROPERTY>
    <PROPERTY name="every" type="int">20</PROPERTY>
    <PROPERTY name="difference" type="int">20</PROPERTY>
      </GROUP>

    <!-- Added for MKP91157 Starts -->
    <GROUP name="ApplogDBUpdateTracker">              
              <PROPERTY name="class" type="String">com.singaporeair.mysia.arch.logging.ApplogDBUpdateSchdeuler</PROPERTY>
              <PROPERTY name="server1At" type="String">01:00:00</PROPERTY>          
              <PROPERTY name="akamai_audit" type="String">/prod/applc/wls/sqdirect/sqdirect/dist/logs/akamai_audit.log</PROPERTY>
        <PROPERTY name="amadeus_audit" type="String">/prod/applc/wls/sqdirect/sqdirect/dist/logs/amadeus_audit.log</PROPERTY>
        <PROPERTY name="blacklistedip" type="String">/prod/applc/wls/sqdirect/sqdirect/dist/logs/blacklistedip.log</PROPERTY>
        <PROPERTY name="pricing_od_fpCount" type="String">/prod/applc/wls/sqdirect/sqdirect/dist/logs/pricing_od_fpCount.log</PROPERTY>
        <PROPERTY name="dateFormat" type="String">yyyy-MM-dd</PROPERTY>
        <PROPERTY name="report_name" type="String">SAA_APPLOG_UPDATE</PROPERTY>
      </GROUP>
<!-- Added for MKP91157 Ends -->


   <GROUP name="PaymentTracker">
        <!-- Sets the payment tracker schedule -->
        <PROPERTY name="class" type="String">com.singaporeair.mysia.paymenttracker.PaymentTrackerScheduler</PROPERTY>
    <PROPERTY name="every" type="int">20</PROPERTY>
    <PROPERTY name="difference" type="int">20</PROPERTY>
      </GROUP>

    <!-- Start 01 Scheduled job for house keeping of barcode images for 2DBP -->

   
  
    <!-- End 01 Scheduled job for house keeping of barcode images for 2DBP -->

     <!-- Added for MKP91488 - Inclusion of more titles -->
     <GROUP name="TitleInclusionDailyScheduler">
        <PROPERTY name="class" type="String">com.singaporeair.mysia.util.TitleIncludeScheduler</PROPERTY>
        <PROPERTY name="at" type="String">01:30:00</PROPERTY>
     </GROUP>
     <!-- Added for MKP91488 - Inclusion of more titles -->


    <!-- Start of Scheduled job for Downloading OD pairs from MARMS -->
       <!-- End of Scheduled job for Downloading OD pairs from MARMS -->


    <GROUP name="DBErrorLoggingReportSchdeuler">
        <PROPERTY name="class" type="String">com.singaporeair.mysia.arch.logging.DBErrorLoggingReportSchdeuler</PROPERTY>
    <PROPERTY name="every" type="String">03:00:00</PROPERTY>
      </GROUP>

    <!-- Added for MKP91158 Starts -->
      <GROUP name="FraudulentEmailLoggingReportSchdeuler">
        <PROPERTY name="class" type="String">com.singaporeair.mysia.arch.logging.FraudulentEmailLoggingReportSchdeuler</PROPERTY>
    <PROPERTY name="every" type="String">01:00:00</PROPERTY>
      </GROUP>
    <!-- Added for MKP91158 Ends -->

    <!-- MKP 91226 Linking SQ Booking Engine to MI Sambath -->
    <GROUP name="DeepLinkEmailLoggingReportSchdeuler">
      <PROPERTY name="class" type="String">com.singaporeair.mysia.arch.logging.DeepLinkEmailLoggingReportSchdeuler</PROPERTY>
      <PROPERTY name="every" type="String">01:00:00</PROPERTY>
    </GROUP>
    <!-- MKP 91226 Linking SQ Booking Engine to MI Sambath -->
     <!-- Sets the schedule to generate the new tax codes email-->
    <GROUP name="SAA_NEW_TAXCODES_SCHEDULER">
      <PROPERTY name="class" type="String">com.singaporeair.mysia.util.GenerateNewTaxCodesEmail_Scheduler</PROPERTY>
      <PROPERTY name="at" type="String">01:00:00</PROPERTY>       
       </GROUP>

    </GROUP>
    <!-- end scheduler -->
      <!-- Start formValidator-->
      <GROUP name="FormValidator">
        <GROUP name="HTMLTags">
          <PROPERTY name="newformpadding" type="String"/>
          <PROPERTY name="passedpadding" type="String"><![CDATA[<font color="blue"><B> </B></font>&nbsp]]></PROPERTY>
          <PROPERTY name="failedpadding" type="String"><![CDATA[<font color="red"><B> </B></font>&nbsp]]></PROPERTY>
          <PROPERTY name="optionalmarker" type="String"/>
          <PROPERTY name="requiredmarker" type="String"/>
        </GROUP>
        <!-- The Client Side Validation -->
        <GROUP name="Client Display Method">
          <PROPERTY name="jspath" type="String">/</PROPERTY>
          <PROPERTY name="jsfile" type="String">displaymessage.js</PROPERTY>
        </GROUP>
        <!-- end of Client Side Validation -->
        <PROPERTY name="clientsidevalinclude" type="boolean">false</PROPERTY>
        <PROPERTY name="emptyfieldsreturnnull" type="boolean">false</PROPERTY>
        <PROPERTY name="maxbusinessactions" type="int">20</PROPERTY>
        <PROPERTY name="hiddenformidentifier" type="String">cffvhidformid</PROPERTY>
        <PROPERTY name="minemaillength" type="int">5</PROPERTY>
        <PROPERTY name="locktimeoutms" type="int">30000</PROPERTY>
        <PROPERTY name="xmlpath" type="String">/prod/applc/wls/sqdirect/sqdirect/dist/config/</PROPERTY>
        <PROPERTY name="rulefile" type="String">rule.xml</PROPERTY>
        <PROPERTY name="xmlfile" type="String">formvalidator.xml</PROPERTY>
        <PROPERTY name="chkDate" type="String">dd/mm/yyyy</PROPERTY>
        <PROPERTY name="errMark" type="String"/>
        <PROPERTY name="maxdispatchpages" type="int">20</PROPERTY>
      </GROUP>
      <!-- end formValidator-->

    <!-- Start 02 of 2DBP reading bp congif files -->

    <GROUP name="BPConfig">
